### ISSUE TITLE
Default sort column in template

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/VueDatatable#71]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Allow the table template to include a default column for sorting

**Comment by aocneanu** [comment]
We discussed about this in the past and we concluded that it's not really a desirable feature.

Maybe you can share some scenarios where this would be needed or useful.

(now you can set the default sort order directly in your TableBuilder )

**Comment by stevefrost** [comment]
I have a table that shows events in chronological order, the data needs to be sorted by date, and not allow the user to change the sort.

**Comment by aocneanu** [comment]
In your query add `orderBy('table.date_column')` and in your json template remove the `sortable` attribute from that column

**Comment by aocneanu** [comment]
Can we close this one?

**Comment by stevefrost** [comment]
"Method Illuminate\Database\Query\Builder::sortBy does not exist."

**Comment by aocneanu** [comment]
:)) ok, `orderBy` I meant.

**Comment by stevefrost** [comment]
adding an orderBy to the query breaks all the other column sorts.

**Comment by aocneanu** [comment]
It should not break anything, is like having the sort from the table component without the option to cancel or revert it.

**Comment by stevefrost** [comment]
Ah, maybe I need something different then, I'd like to be able to set a certain column in the table component to be sorted by default.

**Comment by aocneanu** [comment]
I'm not sure that this two make sense together

>having the sort from the table component without the option to cancel or revert it.

and

>allow normal column sorting to order ride it

**Comment by stevefrost** [comment]
Our conversation diverged on the 23rd  July.
Originally I asked about allowing a fixed sort on a table, which was fixed by the orderBy in the query.

We then started talking about a default sort. This is what I am referring to now.

**Comment by aocneanu** [comment]
Ah, got it now. So now we're talking only about the ability to have a first time sort for a user, sort that can / will be overwritten once the user will configure the table according to its preference. As I said in the beginning we don't think it's a desirable / needed feature, so I will close this again :)

**Comment by jlsjonas** [comment]
> we don't think it's a desirable / needed feature

May I ask why? We're dealing with the same blocker right now: we need to sort by date in reverse (newest first). But we don't want to limit the ability to choose a custom sorting; however if we just do an orderBy in the query, the sortables just don't do anything anymore as the order is already locked in.

As we know 99% of our userbase will want this reverse-chronological order, but some might want/need a custom one this sounds very much like a desirable feature.

**Comment by aocneanu** [comment]
we have now "sort:ASC:" || "sort"DESC" available in the template

**Comment by Al3xR0** [comment]
Hi @aocneanu 

I tried putting sort:ASC property in meta array (template.json) but still does not sort the table. It only shows the icon of ordering in the right position, but the table is the same.

**Comment by jlsjonas** [comment]
Confirming there's an issue with the default sort not applying.
