### ISSUE TITLE
Undefined $Router when trying to attach "action": "router" in the JSON

### ISSUE THREAD

**Issue by jordilanctot** [laravel-enso/VueDatatable#73]
This is  a bug.

### Prerequisites
* [ yes ] Are you running the latest version?
* [ yes ] Are you reporting to the correct repository?
* [ yes ] Did you check the documentation?
* [ yes ] Did you perform a cursory search?

### Description
I have successfully integrated VueDatatable into my Laravel project as a component and I have a table loading into the VueTable.Vue as a component on one of my pages along with data from my database. I am currently running into an issue when attempting to use the router action on the show, edit, delete, etc. buttons in the table where it indicates: 

`TableBody.vue?4729:209   Uncaught TypeError: Cannot read property 'push' of undefined`

Which is the line:

`if (button.action === 'router') {
      this.$router.push({ name: button.route, params: this.getRouteParams(button, row) });
 }`

This seems to indicate that $router is not being defined but when I try and define it in my app.js with:

`//** VUE and VUE-ROUTER **//
  window.Vue = require('vue');
  import VueRouter from 'vue-router';
  Vue.use(VueRouter);`

it indicates that the router cannot be defined again with the error:

`Uncaught TypeError: Cannot redefine property: $router`

### Steps to Reproduce
I'm not sure how to reproduce the error as I have followed the documentation

### Expected behavior
Load this.$router on page init

### Actual behavior
this.$router was undefined and thereby breaking the .push function on it.

**Comment by aocneanu** [comment]
It seems to be related to your specific env.

Are you sure that the router works correctly?

Try the following:
- open your browser console and go to vue dev tools tab 
- select any vue component
- write in the console `$vm0.$router` and press enter

Do you get an error or something similar to the pic below?

![image](https://user-images.githubusercontent.com/16073274/43181248-d1e68da6-8fe4-11e8-8ad0-c5157d60e1b5.png)

**Comment by jordilanctot** [comment]
My mistake; it turns out the issue was that I did not include the required files in my resources/assets. I had noticed your example table view had included: 

`<link href="{{ mix('css/enso.css') }}" rel="stylesheet" type="text/css"/>`
&
`<script src="{{ mix('js/tableExample.js') }}"></script>`

and I had mistakenly put them in my public folder and referenced them using instead:

`<link href="/css/enso.css" rel="stylesheet" type="text/css"/>`
&
`<script src="/js/tableExample.js"></script>`

and not included any of the files in the assets folder thinking the php artisan vendor:publish commands had handled moving all required assets.

Thanks for your speedy reply! I will close the issue, since it is solved. 

I may just not have seen where in the documentation it references the router files in the assets folder. If it is just assumed based on your statement that this package assumes folks aren't beginners, perhaps you might consider putting also putting something that indicates that vue-router is used to handle button clicks and to check the assets folder in the enso-master download for examples.

**Comment by kmcelwrath** [comment]
@jordilanctot Thank you for creating this thread because I am getting the same exact error.  

TableBody.vue?4729:209 Uncaught TypeError: Cannot read property 'push' of undefined.  What exactly did you have to do to make it work?  Only show/edit/create have this issue.

I followed your steps above and included the files in resources/assets and I still get the same error.  I also went to the vue dev tools tab, selected TableBody, and wrote $vm0.$router in the console. When I pressed enter, the result was undefined.

Any help is appreciated. I've been stumped on this for days.

**Comment by jordilanctot** [comment]
@kmcelwrath I'm not super versed in vue router but from what i've read (and I may be, mistaken but...), the issue that you are experiencing is that you need to create vue router files which makes vue router take over the handling routes and stops your laravel web.php from doing it. This means you need to refer to the folders in the resources/js in the full laravel enso example files (routes folder, pages folder, etc.). You may want to use the href option in VueDatatable instead if you don't want to have to learn how to create vue router files. I think you can still use VueDatatable with hrefs that direct you to pages for your crud functions by storing ids in the url. Still looking through all of this stuff and quite new to Laravel though so I don't know how much service I can be.
